[package]
name = "carcinisation_core"
version = "0.2.0"
edition = "2021"

[dependencies]
assert_assets_path = { workspace = true }
bevy = { workspace = true }
derive-new = { workspace = true }
lazy_static = { workspace = true }
seldom_pixel = { workspace = true, features = ["line"] }
