[package]
name = "activable"
edition = "2021"
version.workspace = true

[dependencies]
bevy = { workspace = true }
bevy_ecs = { workspace = true }
bevy_state = { workspace = true }
activable_macros = { path = "../activable_macros" }

[lints]
workspace = true
