[package]
name = "carcinisation"
version = "0.2.0"
edition = "2021"

[features]
default = []
derive-ts = ["ts-rs"]

[dependencies]
assert_assets_path = { workspace = true }
bevy = { workspace = true }
bevy_state = { workspace = true }
bevy_ecs = { workspace = true }
bevy_common_assets = { workspace = true }
bevy-inspector-egui = { workspace = true }
bevy_framepace = { workspace = true }
colored = { workspace = true }
derive-new = { workspace = true }
derive_more = { workspace = true }
lazy_static = { workspace = true }
leafwing-input-manager = { workspace = true }
num_enum = { workspace = true }
rand = { workspace = true }
seldom_pixel = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }
serde-reflection = "0.4"
serde-generate = "0.26"
ts-rs = { workspace = true, optional = true }
anyhow = { workspace = true }
activable-macros = { path = "../../crates/activable-macros" }
activable = { path = "../../crates/activable" }
strum = { workspace = true }
strum_macros = { workspace = true }
[target.'cfg(all(target_family = "wasm", any(target_os = "unknown", target_os = "none")))'.dependencies]
wasm-bindgen = "0.2.92"
getrandom = { version = "0.2", features = ["js"] }

[[bin]]
name = "gen_types"
path = "src/bin/gen_types.rs"

[[bin]]
name = "ron_bridge"
path = "src/bin/ron_bridge.rs"
