[package]
name = "assert_assets_path"
version = "0.1.0"
edition.workspace = true
description = "Compile-time asset path validator"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
